### PR TITLE
Restructuring and extension on the templating documentation.

### PR DESCRIPTION
**Pull request by mpwaldhorst**

### CODE REVIEW

**Comment by mpwaldhorst** [comment]
TODO:

- Language tag
- Form tag
- Include/implement
- Use cases/examples

**Comment by ttveldhuis** [comment]
Does this require merging or is this setup to keep track of changes for now?

**Comment by mpwaldhorst** [comment]
@ttveldhuis for now still WIP, wanted to finish up on the tag documentation at least, maybe do use cases & examples separately.

**Comment by mpwaldhorst** [comment]
@ttveldhuis Added some additional documentation about the tags. There is of course some room for improvement there. But there is now at least a start :)

I will open separate issues regarding use-cases, Addons and Configuration documentation.

In the meantime please review the documentation regarding Language tags, forms and include/implement as these are the more complicated features of Xentriq.

**Comment by ttveldhuis** [comment]
In the documentation for the form tag, under [Providing HTML Attributes](https://xentriqdocs.readthedocs.io/en/templating-docs/templates/tags/form.html#providing-html-attributes) The following warning is issued;

> The implication of the above statement should be clear. It is important not to put any secret information inside arguments on the form-tag as they will be rendered as-is into the HTML.

This is not correct, there are whitelisted attributes that will be rendered to the HTML-tag, at the time of writing these are;

* accept
* accept-charset
* action
* autocomplete
* enctype
* method
* name
* novalidate
* target
* onsubmit

**Pull request merged**
